// The Cal Beta roster, forked from `../chapter-app/lib/data/mock.ts` the same
// way `../points-app` forked it. A fork, not a shared table: the dues app has
// its own Supabase project, and roster drift between the apps is accepted.
// Alumni are excluded — they're lineage-only and don't owe chapter dues.

export type RosterStatus = 'active' | 'new';

export interface RosterEntry {
  name: string;
  status: RosterStatus;
}

export const ROSTER: RosterEntry[] = [
  { name: "Joshua Koch", status: 'active' },
  { name: "Saul Hernandez Vigil", status: 'active' },
  { name: "Lundeen Cahilly", status: 'active' },
  { name: "Graham Johnstone", status: 'active' },
  { name: "Zachary Ewing", status: 'active' },
  { name: "Sam Shors", status: 'active' },
  { name: "Sam Cousins", status: 'active' },
  { name: "Andrew Leick", status: 'active' },
  { name: "Benji Warburton", status: 'active' },
  { name: "Cooper Tenney", status: 'active' },
  { name: "Eddy Duran", status: 'active' },
  { name: "Efrain Angon-Cruz", status: 'active' },
  { name: "Kyle Schmoyer", status: 'active' },
  { name: "Tuvana Soronzonbold", status: 'active' },
  { name: "Mateo Solis", status: 'active' },
  { name: "Jose Berdeja", status: 'active' },
  { name: "Vivek Yarlagedda", status: 'active' },
  { name: "Panos Papanastasiou", status: 'active' },
  { name: "Taden Horse", status: 'active' },
  { name: "Arjin Claire", status: 'active' },
  { name: "Jackson Moyer", status: 'active' },
  { name: "Alex Wohlberg", status: 'active' },
  { name: "Brooks Modesitt", status: 'active' },
  { name: "Jasper Karlson", status: 'active' },
  { name: "Owen Grossman", status: 'active' },
  { name: "Connor Lee", status: 'active' },
  { name: "Ben McAulay", status: 'active' },
  { name: "Blake Pigott", status: 'active' },
  { name: "Chris Vinasco-Gomez", status: 'active' },
  { name: "Jonas Pao", status: 'active' },
  { name: "James Ubi", status: 'active' },
  { name: "Dean Cureton", status: 'active' },
  { name: "Shawn Gregory", status: 'active' },
  { name: "Zack Ryan", status: 'active' },
  { name: "Michael Hemker", status: 'active' },
  { name: "Mercer Weis", status: 'active' },
  { name: "Gerardo Murga", status: 'active' },
  { name: "Peter McGinnes", status: 'active' },
  { name: "Dean Liang", status: 'active' },
  { name: "Griffin Lee", status: 'active' },
  { name: "Alexander Daix", status: 'active' },
  { name: "Alejandro Darbeloff", status: 'active' },
  { name: "No\u00e9 Mart\u00ednez", status: 'active' },
  { name: "Dylan Sih", status: 'active' },
  { name: "Thijs Simonian", status: 'active' },
  { name: "Patrick Walsh", status: 'active' },
  { name: "Abraham Yeung", status: 'active' },
  { name: "Alexander Belfiore", status: 'active' },
  { name: "Carlos Valencia Garcia", status: 'active' },
  { name: "Michael Dolan", status: 'active' },
  { name: "Josh Barsoian", status: 'active' },
  { name: "Carter Dessommes", status: 'active' },
  { name: "Jonathan Morales", status: 'active' },
  { name: "Jai Agrawal", status: 'active' },
  { name: "Christian Pierre", status: 'active' },
  { name: "Aaron Lee", status: 'active' },
  { name: "Dilan Gohill", status: 'active' },
  { name: "Jonathan Tubb", status: 'active' },
  { name: "Zhikai Huang", status: 'active' },
  { name: "George Porteous", status: 'active' },
  { name: "Bradley Bush", status: 'active' },
  { name: "Henry Boeschen", status: 'active' },
  { name: "Aaron Tiao", status: 'active' },
  { name: "Benjamin Chen", status: 'active' },
  { name: "Sam Jonker", status: 'active' },
  { name: "Zaydan Amanullah", status: 'active' },
  { name: "Jason Zhang", status: 'active' },
  { name: "Yannick Mofor", status: 'active' },
  { name: "Kristopher Luo", status: 'active' },
  { name: "Ben Vu", status: 'new' },
  { name: "Bison McCotter-Hulett", status: 'new' },
  { name: "Burkson Montague-Alamin", status: 'new' },
  { name: "Carson Packard", status: 'new' },
  { name: "Connor Engstrom", status: 'new' },
  { name: "Benjamin Schindler", status: 'new' },
  { name: "Sanjay De Silva", status: 'new' },
  { name: "William Maher", status: 'new' },
  { name: "Shrish Premkrishna", status: 'new' },
  { name: "Charles Simonian", status: 'new' },
  { name: "Tej Kosaraju", status: 'new' },
  { name: "Arun Tamura", status: 'new' },
  { name: "Angel Zavala", status: 'new' },
  { name: "Rhett Hounsell", status: 'new' },
  { name: "Ryan Tellado", status: 'new' },
  { name: "Aaron Henschel", status: 'new' },
  { name: "Kushal Patel", status: 'new' },
  { name: "Nigel Willacy", status: 'new' },
  { name: "Joseph Zhang", status: 'new' },
  { name: "Jan Dwayne Cacnio", status: 'new' },
  { name: "Marlon Moenius", status: 'new' },
  { name: "August Hazel", status: 'new' },
  { name: "Jason Wang", status: 'new' },
  { name: "Gael Martinez", status: 'new' },
  { name: "Daniel Tauhert", status: 'new' },
  { name: "Clifford Palmer", status: 'new' },
  { name: "Angel Velasquez", status: 'new' },
  { name: "Diego Seligman-Tovar", status: 'new' },
  { name: "Martin Amaya", status: 'new' },
  { name: "Dylan Dominguez", status: 'new' },
  { name: "Ivan Ho", status: 'new' },
  { name: "Bauer Lee", status: 'new' },
  { name: "Simon Meyers", status: 'new' },
  { name: "Chris Benitez", status: 'new' },
  { name: "Tyler Rubenstein", status: 'new' },
  { name: "Romir Jain", status: 'new' },
];
